### PR TITLE
Ready for Review

### PR DESCRIPTION
**Pull request by Morrism1**
## Restaurant Page Review

- Created required Html nodes in form of modules and exported them
- Imported them into the index.js file
-  Created logic inside the index.js file for creating Tabbing feature of the project

[Live Demo](https://morrism1.github.io/restaurant-page/) 🚀

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @Morrism1! I commend you for writing descriptive commit messages and your use of webpack is impressive. However, I have noticed that you might not have followed the steps given to build this project as outlined in the given guidelines. Check out the points below for a more elaborative description:

- [ ] You should append HTML elements to the `<div>` with `id=content` when the page is loaded ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)).
- [ ] Your `dict` folder should have a `main.js` file that is built by webpack. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/dist_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))

__N.B:__ Much as your current project implementation is fully functional, please note that in the real work environment it is important to follow the requirements as is since other colleagues depend on it to contribute to the same work.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by Morrism1** [comment]
> ### Changes Required! ♻️
> Hi @Morrism1! I commend you for writing descriptive commit messages and your use of webpack is impressive. However, I have noticed that you might not have followed the steps given to build this project as outlined in the given guidelines. Check out the points below for a more elaborative description:
> 
> * [ ]  You should append HTML elements to the `<div>` with `id=content` when the page is loaded ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)).
> * [ ]  Your `dict` folder should have a `main.js` file that is built by webpack. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/dist_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
> 
> **N.B:** Much as your current project implementation is fully functional, please note that in the real work environment it is important to follow the requirements as is since other colleagues depend on it to contribute to the same work.
> 
> **Kindly make the necessary changes and submit another code review request.**
> _Feel free to reach me on slack for any inquiries about this review._ 😉
> **Treasure Kabareebe**
> [Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

Thanks for the Review Treasure, I used some of my previous configs in my Webpack that's why I have that difference.
I will have to follow the requirements as of now 👌.

**Comment by Morrism1** [comment]
Implemented the required changes, Looking for another Review

- Changed the output of JS file from bundle.js to main.js
- Changed the appended the HTML Element `div` from `app` to `content` as required by the Odin project.

**Review by Forison — APPROVED** [review]
## Status::Approved✔️
### Good job on addressing the issue raised in the previous review, you are now appending everything to element with id="content" and main is found in the dist folder😇.
#### Happy coding😎 
Addo Forison

**Pull request merged**
